### ISSUE TITLE
MobCannon issue - my mistake

### ISSUE THREAD

**Issue by pookeythekid** [JOSHSLAYDE/MVPGadgets#7]
Just now, playing on my test server, I found out that my MobCannon doesn't disable mob drops. At the moment, I don't have much time on my hands to find out how to fix that and implement that discovery, so if someone knows how to do this with spawned entities (without disabling every mob drop on the server) I'd appreciate the favor.

**Comment by TGRHavoc** [comment]
I think I may have fixed this with 3 more lines of code added to you class.
If you feel that there is a more efficient/better way of doing what you wanted, feel free to revert the changes :smile:
